### PR TITLE
Added favicon

### PR DESCRIPTION
**Pull request by lord-cyclone100**
###### Before
Screenshot 2024-10-02 220928

###### After
Screenshot 2024-10-02 221015

## Description

Designed and Added the favicon

## Limitations

None

## Checklist

- [x] my PR is focused and contains one wholistic change
- [x] I have added screenshots or screen recordings to show the changes

### CODE REVIEW

**Comment by lord-cyclone100** [comment]
@yurijmikhalevich pls review my pr 
issue #44 
when you merge pls add the hacktoberfest-accepted label
Thanks!!

**Comment by lord-cyclone100** [comment]
@yurijmikhalevich 
Pls check this pr

**Comment by yurijmikhalevich** [comment]
@lord-cyclone100, can you please show how it looks with the light system theme? I suspect yellow on white won't look good.

**Comment by lord-cyclone100** [comment]
@yurijmikhalevich 
I used the website colors.....
Can you pls suggest me the colors that u like?
I would do that according to ur colors
Thanks!!

**Comment by yurijmikhalevich** [comment]
@lord-cyclone100, I think the colors are fine.

@Misofser can help you with the colors more (she will most likely respond over the weekend).

No matter which colors we use, we should make sure that favicon looks good both in the light browser theme and in the dark browser theme because the user may have either.

E.g., this isn't readable:
image

**Review by yurijmikhalevich — CHANGES_REQUESTED** [review]
We need to make sure that favicon is readable both in dark and light browser themes.

**Comment by lord-cyclone100** [comment]
Ok i will make sure about that
Thanks
@yurijmikhalevich

**Comment by yurijmikhalevich** [comment]
Closing in favor of #52.

**Pull request closed without merging**
